### ISSUE TITLE
Abuout ialltoallv in IntelMPI 2021.5.1

### ISSUE THREAD

**Issue by HSUAN221** [rabauke/mpl#33] opened 2023-02-22 08:58 UTC
In the ialltoallv in-place version, the base function "ialltoallv_task" you use the original mpi api "MPI_Ialltoallw" to implement.
![image](https://user-images.githubusercontent.com/48273316/220569056-39d77ede-ba55-4473-8ae6-cc283833f7dd.png)
And, i try to use IntelMPI 2021.5.1 as the base tool, find the case of unit test "ialltoallv_in_place_with_displacements_test" is fail.
Beside that, i try to use openmpi to implement same code is pass, as shown below:
```cpp=1
#include <iostream>
#include <vector>
#include "mpi.h"
int main(int argc, char* argv[]) {
    int N_processes, rank;
    MPI_Init(&argc, &argv); 
    MPI_Comm_size(MPI_COMM_WORLD, &N_processes);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    using T = int;
    T val = 1.0;
    T send_val{val};

    std::vector<T> sendrecv_data;
    std::vector<int> counts(3, 1);
    std::vector<MPI_Datatype> datatypes;
    std::vector<int> recv_disps_int;

    for (int i = 0; i <rank; ++i)
        ++send_val;
    int displ{0};
    for (int j = 0; j < N_processes; ++j) {
        const int N_sendrecv{j + rank + 1};  // must be symmetric in j and rank
        for (int i{0}; i < N_sendrecv; ++i) {
            sendrecv_data.push_back(send_val);
        }
        MPI_Datatype new_type;
        MPI_Type_contiguous(N_sendrecv, MPI_INT, &new_type);
        MPI_Type_commit(&new_type);
        datatypes.push_back(new_type);

        recv_disps_int.push_back(sizeof(T) * displ);
        displ += N_sendrecv;
    }

    MPI_Request req1;
    MPI_Ialltoallw(
        MPI_IN_PLACE,
        nullptr,
        nullptr,
        nullptr,
        sendrecv_data.data(),
        counts.data(),
        recv_disps_int.data(),
        datatypes.data(),
        MPI_COMM_WORLD,
        &req1);
    MPI_Wait(&req1, MPI_STATUS_IGNORE);

    if (rank == 0) {
        std::cout << "sendrecv_data.size()= " << sendrecv_data.size() << std::endl;
        for (size_t i{0}; i < sendrecv_data.size(); ++i) {
            std::cout << sendrecv_data[i] << " ";
        }
        std::cout <<  std::endl;
    }

    MPI_Finalize();
    return 0;
}
```
So, here are my test results. Thanks

**Comment by rabauke** [comment] 2023-02-22 21:46
@HSUAN221 Thanks for your bug report.  This appears to be an issue of Intel's MPI implementation.  This bug might be related to https://github.com/pmodels/mpich/issues/6404, though I am not sure if Intel's MPI implementation is an MPICH derivative.

Maybe one should exclude the failing tests if Intel MPI is employed, similar to https://github.com/rabauke/mpl/commit/82a74801e04d200fe9deb45d8fdfa38c40b48340

**Comment by rabauke** [comment] 2023-02-22 22:25
I am unable to reproduce the failing unit test with Intel(R) MPI Library, Version 2021.8  Build 20221129 and the latest version of MPL from the Git master branch.  I think this has been fixed via https://github.com/rabauke/mpl/commit/82a74801e04d200fe9deb45d8fdfa38c40b48340 by disabling the test for MPICH and its derivatives such as Intel MPI.

**Comment by rabauke** [comment] 2023-02-22 23:00
I added a git workflow that compiles MPL and runs the unit test with the latest Intel MPI.  Currently, all test are successful.  (Tests that might fail due to bugs in MPICH and in Intel MPI have been excluded for MPICH/Intel MPI.)

**Closed by rabauke** 2023-02-22 23:00 UTC
